-- =====================================================================
-- BudgetTracker — complete database setup
--
-- Paste this ENTIRE file into the Supabase SQL Editor and press Run, once.
-- It creates every table, security policy, default category and function the
-- app needs. Safe to run more than once: re-running changes nothing.
--
-- Generated from supabase/migrations/ by scripts/build-setup-sql.mjs.
-- Do not edit this file directly — edit the migrations and regenerate.
--
-- Contains 8 migrations, in order:
--   1. 0001_schema.sql
--   2. 0002_rls.sql
--   3. 0003_handle_new_user.sql
--   4. 0004_rate_provenance.sql
--   5. 0005_full_precision_conversion.sql
--   6. 0006_budget_currency.sql
--   7. 0007_seed_brief_lists.sql
--   8. 0008_overview_function.sql
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1/8: 0001_schema.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- International Student Budget Tracker — Schema
-- Supabase / PostgreSQL migration 0001
--
-- Tables: profiles, categories, payment_methods, transactions, exchange_rates
-- RLS:    enabled on every user-data table (user_id = auth.uid())
-- Trigger: auto-create a profile row + seed defaults on new auth user
-- =====================================================================

-- ---------- profiles ----------
create table if not exists public.profiles (
  id              uuid primary key references auth.users(id) on delete cascade,
  study_country   text,
  local_currency  text,
  home_currency   text,
  display_currency text,
  monthly_budget  numeric(14,2),
  onboarded       boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- ---------- categories ----------
create table if not exists public.categories (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  type        text not null check (type in ('expense','income')),
  is_default  boolean not null default false,
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now(),
  unique (user_id, name, type)
);

-- ---------- payment_methods ----------
create table if not exists public.payment_methods (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  is_default  boolean not null default false,
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now(),
  unique (user_id, name)
);

-- ---------- transactions ----------
create table if not exists public.transactions (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users(id) on delete cascade,
  transaction_type   text not null check (transaction_type in ('expense','income')),
  amount             numeric(18,2) not null check (amount >= 0),
  currency           text not null,
  converted_amount   numeric(18,2),
  converted_currency text,
  exchange_rate      numeric(18,8),
  transaction_date   date not null,
  category_id        uuid references public.categories(id) on delete set null,
  title              text not null,
  description        text,
  payment_method_id  uuid references public.payment_methods(id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists transactions_user_date_idx
  on public.transactions(user_id, transaction_date desc);
create index if not exists transactions_user_category_idx
  on public.transactions(user_id, category_id);
create index if not exists transactions_user_type_idx
  on public.transactions(user_id, transaction_type);

-- ---------- updated_at trigger helper ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists transactions_updated_at on public.transactions;
create trigger transactions_updated_at
  before update on public.transactions
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 2/8: 0002_rls.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- RLS policies — every user-data table enforces user_id = auth.uid()
-- =====================================================================

-- profiles: a user can only see/update their own profile row (id = auth.uid())
alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- categories
alter table public.categories enable row level security;

drop policy if exists "categories_select_own" on public.categories;
create policy "categories_select_own"
  on public.categories for select
  using (auth.uid() = user_id);

drop policy if exists "categories_insert_own" on public.categories;
create policy "categories_insert_own"
  on public.categories for insert
  with check (auth.uid() = user_id);

drop policy if exists "categories_update_own" on public.categories;
create policy "categories_update_own"
  on public.categories for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "categories_delete_own" on public.categories;
create policy "categories_delete_own"
  on public.categories for delete
  using (auth.uid() = user_id);

-- payment_methods
alter table public.payment_methods enable row level security;

drop policy if exists "payment_methods_select_own" on public.payment_methods;
create policy "payment_methods_select_own"
  on public.payment_methods for select
  using (auth.uid() = user_id);

drop policy if exists "payment_methods_insert_own" on public.payment_methods;
create policy "payment_methods_insert_own"
  on public.payment_methods for insert
  with check (auth.uid() = user_id);

drop policy if exists "payment_methods_update_own" on public.payment_methods;
create policy "payment_methods_update_own"
  on public.payment_methods for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "payment_methods_delete_own" on public.payment_methods;
create policy "payment_methods_delete_own"
  on public.payment_methods for delete
  using (auth.uid() = user_id);

-- transactions
alter table public.transactions enable row level security;

drop policy if exists "transactions_select_own" on public.transactions;
create policy "transactions_select_own"
  on public.transactions for select
  using (auth.uid() = user_id);

drop policy if exists "transactions_insert_own" on public.transactions;
create policy "transactions_insert_own"
  on public.transactions for insert
  with check (auth.uid() = user_id);

drop policy if exists "transactions_update_own" on public.transactions;
create policy "transactions_update_own"
  on public.transactions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "transactions_delete_own" on public.transactions;
create policy "transactions_delete_own"
  on public.transactions for delete
  using (auth.uid() = user_id);

-- Every table above is deny-by-default: RLS is enabled and no policy grants
-- access to another user's rows, so a leaked or malicious client cannot read
-- or write across users even though it holds a valid anon key.


-- ---------------------------------------------------------------------
-- 3/8: 0003_handle_new_user.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- Auto-create profile + seed default categories & payment methods
-- on new auth user signup.
--
-- Runs server-side via a trigger on auth.users — works even when email
-- confirmation is enabled (fires on confirmed signup).
-- =====================================================================

-- Default categories seed array
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  -- 1. Create profile row
  insert into public.profiles (id, onboarded)
  values (new.id, false)
  on conflict (id) do nothing;

  -- 2. Seed default expense categories
  insert into public.categories (user_id, name, type, is_default, sort_order)
  select
    new.id, name, 'expense', true, sort_order
  from (values
    ('Food', 1), ('Groceries', 2), ('Transport', 3), ('Housing', 4),
    ('Utilities', 5), ('Phone & Internet', 6), ('Shopping', 7),
    ('Entertainment', 8), ('Health', 9), ('Education', 10),
    ('Travel', 11), ('Other', 12)
  ) as v(name, sort_order)
  on conflict (user_id, name, type) do nothing;

  -- 3. Seed default income categories
  insert into public.categories (user_id, name, type, is_default, sort_order)
  select
    new.id, name, 'income', true, sort_order
  from (values
    ('Allowance', 1), ('Part-time Job', 2), ('Scholarship', 3), ('Other', 4)
  ) as v(name, sort_order)
  on conflict (user_id, name, type) do nothing;

  -- 4. Seed default payment methods
  insert into public.payment_methods (user_id, name, is_default, sort_order)
  select
    new.id, name, true, sort_order
  from (values
    ('Cash', 1), ('Debit Card', 2), ('Credit Card', 3),
    ('Bank Transfer', 4), ('Mobile Payment', 5)
  ) as v(name, sort_order)
  on conflict (user_id, name) do nothing;

  return new;
end;
$$;

-- Drop + recreate the trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ---------------------------------------------------------------------
-- 4/8: 0004_rate_provenance.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- Phase 2: rate provenance on transactions
--
-- converted_amount / converted_currency / exchange_rate already exist
-- (reserved in 0001). This adds the columns needed to be honest about
-- WHICH rate was used and how much to trust it.
-- =====================================================================

alter table public.transactions
  -- The publication date of the rate actually used. ECB publishes on weekdays
  -- only, so a Saturday transaction resolves to Friday's rate; recording it
  -- makes that auditable rather than invisible.
  add column if not exists rate_date date,
  -- 'frankfurter' | 'er-api' | 'identity' (same-currency), null while pending.
  add column if not exists rate_source text,
  -- True when a CURRENT rate was applied to a PAST date because the historical
  -- rate was unavailable. Such rows are labelled approximate in the UI.
  add column if not exists rate_is_approximate boolean not null default false;

-- Finding rows that still need backfilling must stay cheap as the table grows.
create index if not exists transactions_pending_rate_idx
  on public.transactions(user_id)
  where converted_amount is null;

-- Filter/sort support for the Transactions page.
create index if not exists transactions_user_currency_idx
  on public.transactions(user_id, currency);

-- Case-insensitive text search across title + description.
create index if not exists transactions_search_idx
  on public.transactions
  using gin (to_tsvector('simple', title || ' ' || coalesce(description, '')));


-- ---------------------------------------------------------------------
-- 5/8: 0005_full_precision_conversion.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- Phase 2 fix: converted_amount must hold FULL precision.
--
-- The column was numeric(18,2), which silently rounded every converted value
-- to 2 decimals on write. That breaks the stated rule — full precision in
-- storage, rounding at display only — in two ways:
--
--   1. Zero-decimal currencies (KRW, JPY) and high-precision rates lose real
--      information at the moment of writing.
--   2. Rounding each row before summing accumulates error across a month's
--      totals, so Overview's figures would drift from the true sum.
--
-- numeric with no specified scale keeps whatever precision the value has.
-- `amount` stays numeric(18,2): it is a user-entered figure in a real currency,
-- and 2 decimals is correct for every currency we accept.
-- =====================================================================

alter table public.transactions
  alter column converted_amount type numeric;

-- Rates need more precision than money — a JPY->GBP rate is ~0.00465, and
-- 8 decimals is not enough headroom for very weak currency pairs
-- (e.g. VND->GBP is ~0.000028).
alter table public.transactions
  alter column exchange_rate type numeric;


-- ---------------------------------------------------------------------
-- 6/8: 0006_budget_currency.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- Phase 3 fix: the monthly budget needs its own currency.
--
-- `monthly_budget` was a bare number with no currency recorded. A student in
-- London types 1500 meaning GBP 1,500; Overview compared it against totals
-- denominated in the HOME currency (KRW), producing arithmetically correct
-- nonsense — "1,600,183 KRW over your 1,500 KRW budget (106778.9% of it)".
--
-- The budget is denominated in the LOCAL spending currency: that is what a
-- student thinks in when they set it. It is snapshotted at write time for the
-- same reason as transactions.converted_currency — changing local_currency
-- later must not silently re-denominate an existing budget.
-- =====================================================================

alter table public.profiles
  add column if not exists budget_currency text;

-- Backfill existing rows with the local currency, which is the intended basis.
-- Rows with a budget but no local currency are left null and treated as
-- "unknown basis" by the application rather than guessed at.
update public.profiles
   set budget_currency = local_currency
 where budget_currency is null
   and monthly_budget is not null
   and local_currency is not null;


-- ---------------------------------------------------------------------
-- 7/8: 0007_seed_brief_lists.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- Correct the seeded categories and payment methods to the brief's lists.
--
-- The original seed substituted plausible equivalents and invented entries
-- while dropping requested ones. Requirements, not suggestions:
--
--   Expense: Subscription was missing; Utilities was invented. Several names
--            were paraphrased (Food/Eating Out, Education/Academic).
--   Income:  Salary and Refund were missing. Refund matters structurally —
--            a refund is recorded as income, so the rule had nowhere to land.
--   Payment: Global / Travel Card and Other were missing; Mobile Payment was
--            invented. The target user "uses Wise/Revolut/global travel cards".
--
-- This migration:
--   1. Replaces the signup trigger so NEW users get the brief's lists.
--   2. Backfills EXISTING users with the missing entries.
--   3. Deletes nothing that has transactions against it — an invented category
--      a user has already filed spending under is now their data, not our
--      mistake to erase. Unused invented defaults are removed.
-- =====================================================================

-- ---------- 1. new users ----------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, onboarded)
  values (new.id, false)
  on conflict (id) do nothing;

  -- Expense categories, in the brief's order.
  insert into public.categories (user_id, name, type, is_default, sort_order)
  select new.id, name, 'expense', true, sort_order
  from (values
    ('Groceries', 1), ('Eating Out', 2), ('Academic', 3),
    ('Entertainment / Nightlife', 4), ('Transport', 5), ('Phone / Internet', 6),
    ('Housing / Living', 7), ('Shopping', 8), ('Health', 9), ('Travel', 10),
    ('Subscription', 11), ('Other', 12)
  ) as v(name, sort_order)
  on conflict (user_id, name, type) do nothing;

  -- Income categories, in the brief's order.
  insert into public.categories (user_id, name, type, is_default, sort_order)
  select new.id, name, 'income', true, sort_order
  from (values
    ('Allowance', 1), ('Salary', 2), ('Scholarship', 3), ('Refund', 4), ('Other', 5)
  ) as v(name, sort_order)
  on conflict (user_id, name, type) do nothing;

  -- Payment methods, in the brief's order.
  insert into public.payment_methods (user_id, name, is_default, sort_order)
  select new.id, name, is_default, sort_order
  from (values
    ('Debit Card', true, 1), ('Credit Card', false, 2),
    ('Global / Travel Card', false, 3), ('Cash', false, 4),
    ('Bank Transfer', false, 5), ('Other', false, 6)
  ) as v(name, is_default, sort_order)
  on conflict (user_id, name) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- 2. backfill existing users ----------
-- Every existing profile gets any of the brief's entries it is missing.
insert into public.categories (user_id, name, type, is_default, sort_order)
select p.id, v.name, 'expense', true, v.sort_order
from public.profiles p
cross join (values
  ('Groceries', 1), ('Eating Out', 2), ('Academic', 3),
  ('Entertainment / Nightlife', 4), ('Transport', 5), ('Phone / Internet', 6),
  ('Housing / Living', 7), ('Shopping', 8), ('Health', 9), ('Travel', 10),
  ('Subscription', 11), ('Other', 12)
) as v(name, sort_order)
on conflict (user_id, name, type) do nothing;

insert into public.categories (user_id, name, type, is_default, sort_order)
select p.id, v.name, 'income', true, v.sort_order
from public.profiles p
cross join (values
  ('Allowance', 1), ('Salary', 2), ('Scholarship', 3), ('Refund', 4), ('Other', 5)
) as v(name, sort_order)
on conflict (user_id, name, type) do nothing;

insert into public.payment_methods (user_id, name, is_default, sort_order)
select p.id, v.name, v.is_default, v.sort_order
from public.profiles p
cross join (values
  ('Debit Card', true, 1), ('Credit Card', false, 2),
  ('Global / Travel Card', false, 3), ('Cash', false, 4),
  ('Bank Transfer', false, 5), ('Other', false, 6)
) as v(name, is_default, sort_order)
on conflict (user_id, name) do nothing;

-- ---------- 3. remove UNUSED invented defaults only ----------
-- Anything a user has already filed a transaction against is their data now.
-- Only untouched, invented, still-default rows are removed.
delete from public.categories c
 where c.is_default = true
   and c.name in ('Food', 'Utilities', 'Education', 'Entertainment', 'Housing',
                  'Phone & Internet', 'Part-time Job')
   and not exists (
     select 1 from public.transactions t where t.category_id = c.id
   );

delete from public.payment_methods pm
 where pm.is_default = true
   and pm.name in ('Mobile Payment')
   and not exists (
     select 1 from public.transactions t where t.payment_method_id = pm.id
   );

-- ---------- 4. exactly one default payment method per user ----------
-- The original seed marked EVERY payment method is_default, which left existing
-- users with several "defaults" — the Add page then picks arbitrarily. Normalise
-- to exactly one: Debit Card, which leads the brief's list.
update public.payment_methods set is_default = false where is_default = true;

update public.payment_methods
   set is_default = true
 where name = 'Debit Card';

-- Any user without a Debit Card row (only possible if they deleted it) falls
-- back to their lowest-sorted method, so nobody is left with no default.
update public.payment_methods pm
   set is_default = true
 where pm.id in (
   select distinct on (user_id) id
     from public.payment_methods
    where user_id in (
      select user_id from public.payment_methods
      group by user_id
      having count(*) filter (where is_default) = 0
    )
    order by user_id, sort_order, name
 );


-- ---------------------------------------------------------------------
-- 8/8: 0008_overview_function.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- Overview aggregation as a Postgres function, for the hosted deployment.
--
-- The preview backend computes this in server/overview.mjs. Hosted Supabase has
-- no application server, so the same aggregation runs here, called via RPC.
--
-- Ported deliberately, preserving the properties the tests pin down:
--   * every sum is numeric in SQL — never JS float, never a capped page
--   * month bucketing compares date strings, never constructs a timestamp
--   * converted_amount IS NULL rows are EXCLUDED from totals and counted
--     separately; treating them as 0 would make a total quietly wrong
--   * the budget is converted from its own currency before comparison, and the
--     comparison is SUPPRESSED (null) when no rate is available
--
-- SECURITY INVOKER, so RLS applies to the caller: this function cannot read
-- another user's rows even if called with a forged argument.
-- =====================================================================

create or replace function public.overview_for_month(p_month text)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_month_start date;
  v_month_end   date;      -- exclusive
  v_day int;
  v_prior_month text;
  v_prior_start date;
  v_prior_end   date;      -- inclusive bound for the equal period
  v_current_through date;
  v_clamped boolean := false;

  v_expense numeric := 0;
  v_income  numeric := 0;
  v_prior_expense numeric := 0;
  v_prior_income  numeric := 0;

  v_pending int := 0;
  v_approximate int := 0;

  v_home text;
  v_budget_raw numeric;
  v_budget_currency text;
  v_budget_converted numeric;
  v_budget_was_converted boolean := false;
  v_budget_basis_unknown boolean := false;
  v_rate numeric;

  v_categories jsonb := '[]'::jsonb;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  if p_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then
    raise exception 'invalid month: %', p_month;
  end if;

  v_month_start := (p_month || '-01')::date;
  v_month_end   := (v_month_start + interval '1 month')::date;

  -- Equal-period comparison: 1..today of this month vs 1..the same day of the
  -- prior month, clamped when the prior month is shorter.
  v_day := least(
    extract(day from current_date)::int,
    extract(day from (v_month_end - interval '1 day'))::int
  );
  if p_month <> to_char(current_date, 'YYYY-MM') then
    -- A past month is complete: compare the whole month.
    v_day := extract(day from (v_month_end - interval '1 day'))::int;
  end if;
  v_current_through := v_month_start + (v_day - 1);

  v_prior_month := to_char(v_month_start - interval '1 month', 'YYYY-MM');
  v_prior_start := (v_prior_month || '-01')::date;
  if v_day > extract(day from ((v_prior_start + interval '1 month') - interval '1 day'))::int then
    v_clamped := true;
    v_prior_end := (v_prior_start + interval '1 month') - interval '1 day';
  else
    v_prior_end := v_prior_start + (v_day - 1);
  end if;

  -- ---- current window totals (NULL conversions excluded) ----
  select
    coalesce(sum(converted_amount) filter (where transaction_type = 'expense'), 0),
    coalesce(sum(converted_amount) filter (where transaction_type = 'income'), 0)
  into v_expense, v_income
  from public.transactions
  where transaction_date >= v_month_start
    and transaction_date < v_month_end
    and converted_amount is not null;

  select
    count(*) filter (where converted_amount is null),
    count(*) filter (where rate_is_approximate)
  into v_pending, v_approximate
  from public.transactions
  where transaction_date >= v_month_start
    and transaction_date < v_month_end;

  -- ---- equal-period prior window ----
  select
    coalesce(sum(converted_amount) filter (where transaction_type = 'expense'), 0),
    coalesce(sum(converted_amount) filter (where transaction_type = 'income'), 0)
  into v_prior_expense, v_prior_income
  from public.transactions
  where transaction_date >= v_prior_start
    and transaction_date <= v_prior_end
    and converted_amount is not null;

  -- ---- category breakdown ----
  select coalesce(jsonb_agg(row_to_json(x)::jsonb order by x.total desc), '[]'::jsonb)
  into v_categories
  from (
    select
      t.category_id,
      coalesce(c.name, 'Uncategorised') as category_name,
      sum(t.converted_amount)::text as total,
      count(*)::int as tx_count
    from public.transactions t
    left join public.categories c on c.id = t.category_id
    where t.transaction_date >= v_month_start
      and t.transaction_date < v_month_end
      and t.transaction_type = 'expense'
      and t.converted_amount is not null
    group by t.category_id, c.name
  ) x;

  -- ---- budget, converted from its own currency ----
  select home_currency, monthly_budget, budget_currency
    into v_home, v_budget_raw, v_budget_currency
  from public.profiles where id = v_uid;

  if v_budget_raw is not null then
    v_budget_currency := coalesce(v_budget_currency, v_home);
    if v_budget_currency = v_home then
      v_budget_converted := v_budget_raw;
    else
      -- Freshest rate for the pair, taken from the user's own converted rows.
      -- There is no exchange_rates table: rates are stored per transaction with
      -- their provenance (0004_rate_provenance). Using a rate the user's own
      -- data already demonstrates keeps the budget comparison consistent with
      -- the totals it is compared against.
      select t.exchange_rate into v_rate
      from public.transactions t
      where t.currency = v_budget_currency
        and t.converted_currency = v_home
        and t.exchange_rate is not null
      order by t.rate_date desc nulls last, t.created_at desc
      limit 1;

      if v_rate is null then
        v_budget_converted := null;
        v_budget_basis_unknown := true;
      else
        v_budget_converted := v_budget_raw * v_rate;
        v_budget_was_converted := true;
      end if;
    end if;
  end if;

  return jsonb_build_object(
    'month', p_month,
    'totals', jsonb_build_object(
      'expense', v_expense::text,
      'income',  v_income::text,
      'net',     (v_income - v_expense)::text,
      'monthly_budget', case when v_budget_converted is null
                             then null else v_budget_converted::text end,
      'budget_original', case when v_budget_raw is null
                              then null else v_budget_raw::text end,
      'budget_currency', v_budget_currency,
      'budget_converted', v_budget_was_converted,
      'budget_basis_unknown', v_budget_basis_unknown,
      'budget_remaining', case when v_budget_converted is null
                               then null else (v_budget_converted - v_expense)::text end,
      'display_currency', v_home
    ),
    'categories', v_categories,
    'comparison', jsonb_build_object(
      'prior_month', v_prior_month,
      'current_through_day', v_day,
      'prior_through_day', extract(day from v_prior_end)::int,
      'clamped', v_clamped,
      'prior_expense', v_prior_expense::text,
      'prior_income',  v_prior_income::text,
      'comparable', (v_prior_expense > 0 or v_prior_income > 0)
    ),
    'flags', jsonb_build_object(
      'pending_count', v_pending,
      'approximate_count', v_approximate
    )
  );
end;
$$;

comment on function public.overview_for_month(text) is
  'Monthly overview aggregation. SECURITY INVOKER so RLS restricts rows to the '
  'caller. All arithmetic is SQL numeric; NULL conversions are excluded from '
  'totals and reported via flags.pending_count.';

revoke all on function public.overview_for_month(text) from public;

-- Supabase always has the `authenticated` role. Guard the grant so this
-- migration also applies to a plain Postgres (local dev, CI, the preview
-- backend) instead of aborting on a missing role.
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'grant execute on function public.overview_for_month(text) to authenticated';
  end if;
end $$;


commit;

-- Done. Expected result: "Success. No rows returned".
-- Verify with:  select count(*) from public.categories;   -- 0 until someone signs up
